### ISSUE TITLE
Handle "פארצייכן אלע אלס געליינט" in Notification Dropdown

### ISSUE THREAD

**Issue by KnaperYaden** [chucem/IveltChromeExtension#11]
The extension now deals well with the "צייכן אלע אלס געליינט" on the [Notifications](https://www.ivelt.com/forum/ucp.php?i=ucp_notifications) page:
https://github.com/chucem/IveltChromeExtension/blob/8daefddd3c21610f2818ec355a502f899cb1edcc/extension/js/settingsHandler.js#L26-L38

But the Notification dropdown also has a "פארצייכן אלע אלס געליינט" link, and in there the confirmation popup appears, but the notifications are marked read even if canceled:
![image](https://github.com/chucem/IveltChromeExtension/assets/87161728/6b1825d9-81a0-4c46-bd31-18d71090defb)

The reason seems to be because the link is sent using ```data-ajax="notification.mark_all_read"``` without a page reload, which is not prevented by the confirmation dialog popup.

It'd be cool if someone can come up with a method to handle it even in such case.

**Comment by chucem** [comment]
Fixed with ffb6e259644b23b73ddcf0de30691efbe5faf9cd
